# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# source: https://www.meziantou.net/publishing-a-nuget-package-following-best-practices-using-github.htm

name: publish-nuget
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  run_test:
    name: "🧪 Run Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Run tests
        run: dotnet test --configuration Release

  semantic_nuget_release:
    name: "🚀 Semantic NuGet Release"
    runs-on: ubuntu-latest
    needs: [ run_test ]
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install exec plugin
        run: npm install @semantic-release/exec -D

      # Install the .NET SDK indicated in the global.json file
      # Required by the commands run by the exec plugin
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
